### ISSUE TITLE
Be polite

### ISSUE THREAD

**Issue by sileix** [Stanford-Mobisocial-IoT-Lab/almond-dialog-agent#11]
change "ok forget it" "never mind" etc.

**Comment by gcampax** [comment]
Do you have specific suggestions for those messages in mind?

**Comment by sileix** [comment]
how about this:
never mind -> cancel 
ok forget it -> sorry I couldn't help you on that

**Comment by gcampax** [comment]
Never mind is an input, so you can write whatever you want as long as you train it.

I'm not particularly sold on "Ok forget it", "Sorry I couldn't help you on that" seems fine. Feel free to change it.
