### ISSUE TITLE
Crash if given two commands in a row

### ISSUE THREAD

**Issue by sileix** [Stanford-Mobisocial-IoT-Lab/almond-dialog-agent#29]
While almond expects an answer:

Aug 13 09:12:10 crowdie node[2670]: Almond Says: Sorry, I had an error processing your command: false == true
Aug 13 09:12:10 crowdie node[2670]: AssertionError [ERR_ASSERTION]: false == true
Aug 13 09:12:10 crowdie node[2670]:     at Dispatcher.handle (/opt/thingengine/node_modules/almond-dialog-agent/lib/dispatcher.js:464:9)
Aug 13 09:12:10 crowdie node[2670]:     at <anonymous>
Aug 13 09:12:10 crowdie node[2670]:     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by gcampax** [comment]
Fixed by https://github.com/Stanford-Mobisocial-IoT-Lab/almond-dialog-agent/commit/13fc4b6e9b1107b89f3bb7b593f57c48e12791cc
